CREATE DATABASE IF NOT EXISTS HDBC;
CREATE TABLE `HDBC`.`user`(
    `user_id` INT UNIQUE NOT NULL AUTO_INCREMENT,
    `first_name` VARCHAR(256) NOT NULL,
    `last_name` VARCHAR(256) NOT NULL,
    `email` VARCHAR(256) NOT NULL
    `admin` TINYINT NOT NULL DEFAULT 1
);
